<?php

return array(
    "1-900-FUK-MEUP",
    "110 in the shade",
    "151 Florida Bushwacker",
    "155 Belmont",
    "24k nightmare",
    "252",
    "3 Wise Men",
    "3-Mile Long Island Iced Tea",
    "410 Gone",
    "50/50",
    "501 Blue",
    "57 Chevy with a White License Plate",
    "69 Special",
    "747",
    "747 Drink",
    "9 1/2 Weeks",
    "A Day at the Beach",
    "A Furlong Too Late",
    "A Gilligan's Island",
    "A midsummernight dream",
    "A Night In Old Mandalay",
    "A Piece of Ass",
    "A Splash of Nash",
    "A True Amaretto Sour",
    "A. J.",
    "A.D.M. (After Dinner Mint)",
    "A1",
    "Abbey Cocktail",
    "Abbey Martini",
    "ABC",
    "Abilene",
    "Absinthe #2",
    "Absolut Evergreen",
    "Absolut limousine",
    "Absolut Sex",
    "Absolut Stress #2",
    "Absolut Summertime",
    "Absolutely Cranberry Smash",
    "Absolutely Fabulous",
    "Absolutly Screwed Up",
    "Acapulco",
    "Ace",
    "ACID",
    "Adam",
    "Adam & Eve",
    "Adam Bomb",
    "Adam Sunrise",
    "Addington",
    "Addison",
    "Addison Special",
    "Adios Amigos Cocktail",
    "Adonis Cocktail",
    "Affair",
    "Affinity",
    "After Dinner Cocktail",
    "After Five",
    "After sex",
    "After Supper Cocktail",
    "Afternoon",
    "Alabama Slammer",
    "Alaska Cocktail",
    "Alexander",
    "Alfie Cocktail",
    "Algonquin",
    "Alice in Wonderland",
    "Allegheny",
    "Allies Cocktail",
    "Almeria",
    "Almond Chocolate Coffee",
    "Almond Joy",
    "Amaretto And Cream",
    "Amaretto fizz",
    "Amaretto Liqueur",
    "Amaretto Mist",
    "Amaretto Rose",
    "Amaretto Shake",
    "Amaretto Sour",
    "Amaretto Stinger",
    "Amaretto Stone Sour",
    "Amaretto Stone Sour Alternative",
    "Amaretto Sunrise",
    "Amaretto Sunset",
    "Amaretto Sweet & Sour",
    "Amaretto Tea",
    "Americano",
    "Angel Face",
    "Angelica Liqueur",
    "Aperol Spritz",
    "Apple Grande",
    "Apple Highball",
    "Apple Pie with A Crust",
    "Apple Slammer",
    "Applecar",
    "Applejack",
    "Apricot Lady",
    "Apricot punch",
    "Aquamarine",
    "Archbishop",
    "Arctic Fish",
    "Arctic Mouthwash",
    "Arise My Love",
    "Arizona Antifreeze",
    "Arizona Stingers",
    "Arizona Twister",
    "Army special",
    "Arthur Tompkins",
    "Artillery",
    "Artillery Punch",
    "AT&T",
    "Atlantic Sun",
    "Atomic Lokade",
    "Auburn Headbanger",
    "Autodafé",
    "Autumn Garibaldi",
    "Avalanche",
    "Avalon",
    "Aviation",
    "Aztec Punch",
    "B-52",
    "B-53",
    "Baby Eskimo",
    "Baby Guinness",
    "Bacardi Cocktail",
    "Bahama Mama",
    "Bailey's Dream Shake",
    "Balmoral",
    "Banana Cream Pi",
    "Banana Daiquiri",
    "Barracuda",
    "Bee's Knees",
    "Belgian Blue",
    "Bellini",
    "Bellini Martini",
    "Bermuda Highball",
    "Berry Deadly",
    "Between The Sheets",
    "Bible Belt",
    "Big Red",
    "Bijou",
    "Black & Tan",
    "Black and Brown",
    "Black Forest Shake",
    "Black Russian",
    "Blackthorn",
    "Bleeding Surgeon",
    "Blind Russian",
    "Bloody Maria",
    "Bloody Mary",
    "Bloody Punch",
    "Blue Hurricane",
    "Blue Lagoon",
    "Blue Margarita",
    "Blue Mountain",
    "Blueberry Mojito",
    "Bluebird",
    "Bob Marley",
    "Bobby Burns Cocktail",
    "Bombay Cassis",
    "Boomerang",
    "Boozy Snickers Milkshake",
    "Boston Sidecar",
    "Boston Sour",
    "Boulevardier",
    "Bounty Hunter",
    "Bourbon Sling",
    "Bourbon Sour",
    "Boxcar",
    "Brain Fart",
    "Brainteaser",
    "Bramble",
    "Brandon and Will's Coke Float",
    "Brandy Alexander",
    "Brandy Cobbler",
    "Brandy Flip",
    "Brandy Sour",
    "Brave Bull Shooter",
    "Brigadier",
    "Broadside",
    "Brooklyn",
    "Bruce's Puce",
    "Bruised Heart",
    "Bubble Gum",
    "Buccaneer",
    "Bumble Bee",
    "Butter Baby",
    "Butterfly Effect",
    "Cafe Savoy",
    "Caipirinha",
    "Caipirissima",
    "California Lemonade",
    "California Root Beer",
    "Campari Beer",
    "Captain Kidd's Punch",
    "Caribbean Boilermaker",
    "Caribbean Orange Liqueur",
    "Casa Blanca",
    "Casino",
    "Casino Royale",
    "Champagne Cocktail",
    "Cherry Electric Lemonade",
    "Cherry Rum",
    "Chicago Fizz",
    "Chocolate Black Russian",
    "Chocolate Milk",
    "Citrus Coke",
    "City Slicker",
    "Classic Old-Fashioned",
    "Clove Cocktail",
    "Clover Club",
    "Cocktail Horse’s Neck",
    "Coffee Liqueur",
    "Coffee-Vodka",
    "Corn n Oil",
    "Corpse Reviver",
    "Cosmopolitan",
    "Cosmopolitan Martini",
    "Cranberry Cordial",
    "Cream Soda",
    "Creme de Menthe",
    "Cuba Libra",
    "Cuba Libre",
    "Daiquiri",
    "Damned if you do",
    "Danbooka",
    "Dark and Stormy",
    "Dark Caipirinha",
    "Darkwood Sling",
    "Death in the Afternoon",
    "Derby",
    "Diesel",
    "Dirty Martini",
    "Dirty Nipple",
    "Downshift",
    "Dragonfly",
    "Dry Martini",
    "Dry Rob Roy",
    "Dubonnet Cocktail",
    "Duchamp's Punch",
    "Elderflower Caipirinha",
    "Empellón Cocina's Fat-Washed Mezcal",
    "English Highball",
    "English Rose Cocktail",
    "Espresso Martini",
    "Espresso Rumtini",
    "Fahrenheit 5000",
    "Figgy Thyme",
    "Flaming Dr. Pepper",
    "Flaming Lamborghini",
    "Flander's Flake-Out",
    "Flying Dutchman",
    "Flying Scotchman",
    "Foxy Lady",
    "Freddy Kruger",
    "French 75",
    "French Connection",
    "French Martini",
    "French Negroni",
    "Frisco Sour",
    "Frosé",
    "Frozen Daiquiri",
    "Frozen Mint Daiquiri",
    "Frozen Pineapple Daiquiri",
    "Funk and Soul",
    "Fuzzy Asshole",
    "Gagliardo",
    "Garibaldi Negroni",
    "Gentleman's Club",
    "Gideon's Green Dinosaur",
    "Gimlet",
    "Gin and Soda",
    "Gin And Tonic",
    "Gin Basil Smash",
    "Gin Cooler",
    "Gin Daisy",
    "Gin Fizz",
    "Gin Lemon",
    "Gin Rickey",
    "Gin Sling",
    "Gin Smash",
    "Gin Sour",
    "Gin Squirt",
    "Gin Swizzle",
    "Gin Toddy",
    "Gin Tonic",
    "Girl From Ipanema",
    "Godchild",
    "Godfather",
    "Godmother",
    "Golden dream",
    "Grand Blue",
    "Grass Skirt",
    "Grasshopper",
    "Green Goblin",
    "Greyhound",
    "Grim Reaper",
    "Grizzly Bear",
    "H.D.",
    "Halloween Punch",
    "Happy Skipper",
    "Harvey Wallbanger",
    "Havana Cocktail",
    "Hawaiian Cocktail",
    "Hemingway Special",
    "Herbal flame",
    "Highland Fling Cocktail",
    "Homemade Kahlua",
    "Honey Bee",
    "Horse's Neck",
    "Hot Creamy Bush",
    "Hot Toddy",
    "Hunter's Moon",
    "Ice Pick",
    "Iced Coffee Fillip",
    "Imperial Cocktail",
    "Imperial Fizz",
    "Irish Coffee",
    "Irish Cream",
    "Irish Curdling Cow",
    "Irish Russian",
    "Irish Spring",
    "Jack Rose Cocktail",
    "Jack's Vanilla Coke",
    "Jackhammer",
    "Jam Donut",
    "Jamaica Kiss",
    "Jamaican Coffee",
    "Japanese Fizz",
    "Jello shots",
    "Jelly Bean",
    "Jewel Of The Nile",
    "Jitterbug",
    "John Collins",
    "Kamikaze",
    "Karsk",
    "Kentucky B And B",
    "Kentucky Colonel",
    "Kioki Coffee",
    "Kir",
    "Kir Royale",
    "Kiss me Quick",
    "Kiwi Lemon",
    "Kiwi Martini",
    "Kool First Aid",
    "Kool-Aid Shot",
    "Kool-Aid Slammer",
    "Kurant Tea",
    "Lady Love Fizz",
    "Lazy Coconut Paloma",
    "Lemon Drop",
    "Lemon Elderflower Spritzer",
    "Lemon Shot",
    "Limona Corona",
    "Loch Lomond",
    "London Town",
    "Lone Tree Cocktail",
    "Lone Tree Cooler",
    "Long Island Iced Tea",
    "Long Island Tea",
    "Long vodka",
    "Lord And Lady",
    "Lunch Box",
    "Mai Tai",
    "Malibu Twister",
    "Mango Mojito",
    "Manhattan",
    "Margarita",
    "Martinez 2",
    "Martinez Cocktail",
    "Martini",
    "Mary Pickford",
    "Miami Vice",
    "Michelada",
    "Midnight Cowboy",
    "Midnight Manx",
    "Midnight Mint",
    "Mimosa",
    "Mint Julep",
    "Mississippi Planters Punch",
    "Mocha-Berry",
    "Mojito",
    "Mojito Extra",
    "Monkey Gland",
    "Monkey Wrench",
    "Moranguito",
    "Moscow Mule",
    "Mother's Milk",
    "Mountain Bramble",
    "Mudslinger",
    "Mulled Wine",
    "Munich Mule",
    "National Aquarium",
    "Negroni",
    "New York Lemonade",
    "New York Sour",
    "Nutty Irishman",
    "Oatmeal Cookie",
    "Old Fashioned",
    "Old Pal",
    "Orange Crush",
    "Orange Oasis",
    "Orange Push-up",
    "Orange Rosemary Collins",
    "Orange Whip",
    "Oreo Mudslide",
    "Orgasm",
    "Owen's Grandmother's Revenge",
    "Paloma",
    "Paradise",
    "Passion Fruit Martini",
    "Pegu Club",
    "Penicillin",
    "Pina Colada",
    "Pineapple Paloma",
    "Pink Gin",
    "Pink Lady",
    "Pink Moon",
    "Pink Panty Pulldowns",
    "Pink Penocha",
    "Pisco Sour",
    "Planter's Punch",
    "Planter’s Punch",
    "Popped cherry",
    "Poppy Cocktail",
    "Pornstar Martini",
    "Port And Starboard",
    "Port Wine Cocktail",
    "Port Wine Flip",
    "Porto flip",
    "Pure Passion",
    "Quaker's Cocktail",
    "Quarter Deck Cocktail",
    "Queen Bee",
    "Queen Charlotte",
    "Queen Elizabeth",
    "Quentin",
    "Quick F**K",
    "Quick-sand",
    "Radioactive Long Island Iced Tea",
    "Radler",
    "Ramos Gin Fizz",
    "Raspberry Cooler",
    "Raspberry Julep",
    "Red Snapper",
    "Rose",
    "Rosemary Blue",
    "Royal Bitch",
    "Royal Fizz",
    "Royal Flush",
    "Royal Gin Fizz",
    "Ruby Tuesday",
    "Rum Cobbler",
    "Rum Cooler",
    "Rum Milk Punch",
    "Rum Old-fashioned",
    "Rum Punch",
    "Rum Runner",
    "Rum Screwdriver",
    "Rum Sour",
    "Rum Toddy",
    "Russian Spring Punch",
    "Rusty Nail",
    "Salted Toffee Martini",
    "Salty Dog",
    "San Francisco",
    "Sangria",
    "Sangria The  Best",
    "Sazerac",
    "Scooter",
    "Scotch Cobbler",
    "Scotch Sour",
    "Scottish Highland Liqueur",
    "Screaming Orgasm",
    "Screwdriver",
    "Sea breeze",
    "Sex on the Beach",
    "Shanghai Cocktail",
    "Shark Attack",
    "Sherry Eggnog",
    "Sherry Flip",
    "Shot-gun",
    "Sidecar",
    "Sidecar Cocktail",
    "Singapore Sling",
    "Slippery Nipple",
    "Sloe Gin Cocktail",
    "Smashed Watermelon Margarita",
    "Smut",
    "Snake Bite (UK)",
    "Snakebite and Black",
    "Snowball",
    "Snowday",
    "Sol Y Sombra",
    "Space Odyssey",
    "Spice 75",
    "Spritz",
    "Spritz Veneziano",
    "Stinger",
    "Stone Sour",
    "Strawberry Daiquiri",
    "Strawberry Margarita",
    "Surf City Lifesaver",
    "Swedish Coffee",
    "Sweet Sangria",
    "Sweet Tooth",
    "Talos Coffee",
    "Tennesee Mud",
    "Tequila Fizz",
    "Tequila Slammer",
    "Tequila Sour",
    "Tequila Sunrise",
    "Tequila Surprise",
    "Texas Rattlesnake",
    "Texas Sling",
    "The Evil Blue Thing",
    "The Galah",
    "The Jimmy Conway",
    "The Last Word",
    "The Laverstoke",
    "The Philosopher",
    "The Strange Weaver",
    "Thriller",
    "Tia-Maria",
    "Tipperary",
    "Tom Collins",
    "Tommy's Margarita",
    "Turf Cocktail",
    "Turkeyball",
    "Tuxedo Cocktail",
    "Valencia Cocktail",
    "Vampiro",
    "Van Vleet",
    "Vermouth Cassis",
    "Vesper",
    "Vesuvio",
    "Veteran",
    "Victor",
    "Victory Collins",
    "Vodka And Tonic",
    "Vodka Fizz",
    "Vodka Lemon",
    "Vodka Martini",
    "Vodka Russian",
    "Vodka Slime",
    "Vodka Tonic",
    "Waikiki Beachcomber",
    "Whiskey Sour",
    "Whisky Mac",
    "White Lady",
    "White Russian",
    "White Wine Sangria",
    "Whitecap Margarita",
    "Wine Punch",
    "Winter Paloma",
    "Winter Rita",
    "Yellow Bird",
    "Zambeer",
    "Zenmeister",
    "Ziemes Martini Apfelsaft",
    "Zima Blaster",
    "Zimadori Zinger",
    "Zinger",
    "Zipperhead",
    "Zippy's Revenge",
    "Zizi Coin-coin",
    "Zoksel",
    "Zombie",
    "Zorbatini",
    "Zorro",
    "Afterglow",
    "Alice Cocktail",
    "Aloha Fruit punch",
    "Apello",
    "Apple Berry Smoothie",
    "Apple Karate",
    "Banana Cantaloupe Smoothie",
    "Banana Milk Shake",
    "Banana Strawberry Shake",
    "Banana Strawberry Shake Daiquiri",
    "Bora Bora",
    "Castillian Hot Chocolate",
    "Chocolate Beverage",
    "Chocolate Drink",
    "Coke and Drops",
    "Cranberry Punch",
    "Drinking Chocolate",
    "Egg Cream",
    "Frappé",
    "Fruit Cooler",
    "Fruit Flip-Flop",
    "Fruit Shake",
    "Grape lemon pineapple Smoothie",
    "Holloween Punch",
    "Hot Chocolate to Die for",
    "Iced Coffee",
    "Ipamena",
    "Just a Moonmint",
    "Kill the cold Smoothie",
    "Kiwi Papaya Smoothie",
    "Lassi - A South Indian Drink",
    "Lassi - Mango",
    "Lassi - Sweet",
    "Lassi Khara",
    "Lassi Raita",
    "Lemouroudji",
    "Limeade",
    "Mango Orange Smoothie",
    "Masala Chai",
    "Melya",
    "Microwave Hot Cocoa",
    "Nuked Hot Chocolate",
    "Orange Scented Hot Chocolate",
    "Orangeade",
    "Pineapple Gingerale Smoothie",
    "Pysch Vitamin Light",
    "Rail Splitter",
    "Spanish chocolate",
    "Spiced Peach Punch",
    "Spiking coffee",
    "Strawberry Lemonade",
    "Strawberry Shivers",
    "Sweet Bananas",
    "Thai Coffee",
    "Thai Iced Coffee",
    "Thai Iced Tea",
    "Tomato Tang",
    "Yoghurt Cooler",
);